#
# Pebble Assistant build rules.
#
# The PebbleKit JS side is authored as ordered parts under `src/pkjs/parts/` and
# concatenated here into a single traditional `pebble-js-app.js` bundle.  This is
# deliberate: the Core Devices iOS companion app can hang on "Loading watchapp"
# when the JS entry point is a multi-file/`index.js` bundle, so the shipped PBW
# must always contain one flat, ES5, `pebble-js-app.js` payload.
#
import os.path

top = '.'
out = 'build'

# Concatenation order matters: later parts may call into earlier ones at load
# time, and only `90_main.js` is allowed to register Pebble event listeners.
PKJS_PARTS = [
    '00_util.js',
    '05_settings.js',
    '10_auth.js',
    '20_codex.js',
    '30_caldav.js',
    '35_gmail_notes.js',
    '40_tools.js',
    '50_conversations.js',
    '60_watchlink.js',
    '90_main.js',
]


def bundle_pkjs(task):
    """Concatenate the ordered PKJS parts into one legacy bundle."""
    chunks = ['// Generated by wscript from src/pkjs/parts/ -- do not edit build output.\n']
    for node in task.inputs:
        chunks.append('\n// ---- %s ----\n' % os.path.basename(node.abspath()))
        with open(node.abspath(), 'r', encoding='utf-8') as source:
            chunks.append(source.read())
            chunks.append('\n')
    with open(task.outputs[0].abspath(), 'w', encoding='utf-8', newline='') as target:
        target.write(''.join(chunks))


def options(ctx):
    ctx.load('pebble_sdk')


def configure(ctx):
    ctx.load('pebble_sdk')


def build(ctx):
    ctx.load('pebble_sdk')

    binaries = []
    cached_env = ctx.env
    for platform in ctx.env.TARGET_PLATFORMS:
        ctx.env = ctx.all_envs[platform]
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf = '{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        ctx.pbl_build(source=ctx.path.ant_glob('src/c/**/*.c'),
                      target=app_elf,
                      bin_type='app')
        binaries.append({'platform': platform, 'app_elf': app_elf})
    ctx.env = cached_env

    ctx.set_group('bundle')
    sources = []
    for name in PKJS_PARTS:
        node = ctx.path.find_node('src/pkjs/parts/' + name)
        if not node:
            ctx.fatal('Missing PKJS part: src/pkjs/parts/' + name)
        sources.append(node)

    bundled = ctx.path.get_bld().make_node('pkjs/pebble-js-app.js')
    bundled.parent.mkdir()
    ctx(rule=bundle_pkjs, source=sources, target=bundled, name='bundle_pkjs')

    ctx.pbl_bundle(binaries=binaries,
                   js=[bundled],
                   js_entry_file='build/pkjs/pebble-js-app.js')
